### ISSUE TITLE
Replace CSV with YAML

### ISSUE THREAD

**Issue by manics** [manics/uktre-glossary#1]
For example
```yaml

glossary:

  - term: Example
    tags:
      - Category 1
      - Category 2
    definition: |
      This is an example definition.
      Use two blank lines to start a new paragraph.

      Cross link other glossary terms by putting the term in [square brackets].

      See also: [Access Control]; [Authentication]; [Authorisation].

  - term: AAI
    tags:
      - Security Management
    definition: |
      An abbreviation of "authentication and authorisation infrastructure", AAI refers to the technical mechanisms used to verify and manage users' access to computer systems.

      See also: [Access Control]; [Authentication]; [Authorisation].

  - term: Access Control
    tags:
      - Security Management
    definition: |
      The technical mechanism for controlling a known (authenticated) user’s access to a system and its underlying assets such as data. Access control is also referred to as authorisation (and shorthanded as “AuthZ” to distinguish it from authentication), as it determines what the user is authorised to do.

      See also: [AAI]; [Authentication]; [Authorisation].
```
